---
title: "format"
author: "Rachel Smith"
date: "5/4/2021"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, comment = "")

library(tidyverse)
library(nortest)
library(FSA)
library(tidymodels)
library(factoextra)
library(ggpubr)
library(ggrepel)
library(grid)
library(pheatmap)
library(plotly)
library(corrr)
library(reshape)
library(RColorBrewer)
library(usemodels)
library(ranger)
library(vip)
library(MASS)

```

# Dysregulation of hemoglobin and oxygenation in cerebral malaria {.tabset}

```{r data}

# read in data
df_hbox <- read.csv("Data/98 first visit records with cerebral oxygenation stats_trimmed.csv") %>% as_tibble()

# get rid of "Other"
df_hbox <- df_hbox %>% 
  filter(Status != "Other") %>% 
  mutate(Status = factor(Status, levels = c("HV", "UM", "CM")))

# identify duplicated rows (TM0003, TM2001)
df_hbox <- df_hbox %>% filter(duplicated(Subject.ID..NIAID.) == FALSE)

# Convert age to numeric
df_hbox <- df_hbox %>% 
  mutate(Age = gsub(" Years, ", "_", Age)) %>% 
  mutate(Age = gsub(" Months ", "", Age)) %>% 
  separate(Age, into = c("Years", "Months"), sep = "_") %>% 
  mutate(Years = as.numeric(Years)) %>% 
  mutate(Months = as.numeric(Months)/12) %>% 
  mutate(Age = Years + Months) %>% 
  dplyr::select(-c(Years, Months))

# Convert sex to factor
df_hbox <- df_hbox %>% mutate(Sex = as.factor(Sex))

# Trim for variables of interest (VOI)
df_hbox_trim <- df_hbox %>% 
  dplyr::select(c(Subject.ID..NIAID., Status, Glucose, Hematocrit, Lactate, Temperature,
                  Arginine.umol.L, Haptoglobin..mg.dl., Hemoglobin..uM., Whole.Blood.Nitrite, 
                  cerebral.hbdeox, cerebral.hbdeox.alpha, cerebral.hbox, cerebral.hbox.alpha,
                  cerebral.sat, cerebral.sat.alpha, cerebral.thc, cerebral.thc.alpha, cerebral.thc.norm.std)) %>% 
  
  dplyr::rename("subject_id" = "Subject.ID..NIAID.", "Arginine (umol/L)" = "Arginine.umol.L", "Haptoglobin (mg/dL)" = "Haptoglobin..mg.dl.", 
                "Hemoglobin (uM)" = "Hemoglobin..uM.", "WB_Nitrite" = "Whole.Blood.Nitrite", "DeoxyHb" = "cerebral.hbdeox", 
                "DeoxyHb_alpha" = "cerebral.hbdeox.alpha", "OxyHb" = "cerebral.hbox", "OxyHb_alpha" = "cerebral.hbox.alpha", 
                "O2sat" = "cerebral.sat", "O2sat_alpha" = "cerebral.sat.alpha", "THC" = "cerebral.thc", 
                "THC_alpha" = "cerebral.thc.alpha", "THC_sd" = "cerebral.thc.norm.std") 

# impute missing data with median by group
f_impute <- function(x, na.rm = TRUE) (replace(x, is.na(x), median(x, na.rm = na.rm)))

df_hbox_impute <- df_hbox_trim %>% 
  group_by(Status) %>% 
  mutate_at(3:ncol(.), f_impute) %>% 
  ungroup()

# pivot long
df_hbox_long <- df_hbox_trim %>% pivot_longer(cols = 3:ncol(.), names_to = "measurement", values_to = "value")

```

## One way ANOVAs {.tabset}

### Influence healthy vs malaria

#### Arginine
```{r arginine_show, echo = TRUE, eval = FALSE}

# create model for BoxCox transformation
arg_model <- glm(`Arginine (umol/L)` ~ Status, data = df_hbox_impute)
boxcox(arg_model, lambda = seq(-0.5, 1, by = 0.1), plotit = TRUE)

# BoxCox transform
df_arg <- df_hbox_impute %>% mutate(arg_transform = (`Arginine (umol/L)`^-0.25 - 1)/-0.25)

# model on transformed data
glm(arg_transform ~ Status, data = df_arg) %>% summary()

```

```{r arg_model}

glm(`Arginine (umol/L)` ~ Status, data = df_hbox_impute) %>% summary()

df_hbox_long %>% filter(measurement == "Arginine (umol/L)") %>% 
  
  ggplot(aes(x = Status, y = value)) +
  geom_violin(aes(color = Status)) +
  geom_jitter(position = position_jitter(0.2), shape = 1) +
  stat_summary(fun = "median", geom = "crossbar", aes(color = Status), size = 0.2, width = 0.5) +

  theme_bw() +
  theme(legend.position = "none")  +
  ggtitle("Arginine (umol/L)") +
  
  theme(strip.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        axis.title.y = element_blank(),
        axis.text = element_text(size = 15))



```

#### Temperature
```{r temp}

glm(Temperature ~ Status, data = df_hbox_impute) %>% summary()
aov(Temperature ~ Status, data = df_hbox_impute) %>% TukeyHSD() %>% 
  .$Status %>% 
  as.data.frame() %>% 
  rownames_to_column("Status") %>% 
  dplyr::select(Status, `p adj`)

```

#### Hematocrit
```{r hct}

glm(Hematocrit ~ Status, data = df_hbox_impute) %>% summary()
aov(Temperature ~ Status, data = df_hbox_impute) %>% TukeyHSD() %>% 
  .$Status %>% 
  as.data.frame() %>% 
  rownames_to_column("Status") %>% 
  dplyr::select(Status, `p adj`)

```

### Influence CM vs UM

#### O2sat_alpha
```{r O2sat_alpha}

glm(O2sat_alpha ~ Status, data = df_hbox_impute) %>% summary()
aov(O2sat_alpha ~ Status, data = df_hbox_impute) %>% TukeyHSD() %>% 
  .$Status %>% 
  as.data.frame() %>% 
  rownames_to_column("Status") %>% 
  dplyr::select(Status, `p adj`)

```

#### THC_alpha
```{r THC_alpha}

glm(THC_alpha ~ Status, data = df_hbox_impute) %>% summary()
aov(THC_alpha ~ Status, data = df_hbox_impute) %>% TukeyHSD() %>% 
  .$Status %>% 
  as.data.frame() %>% 
  rownames_to_column("Status") %>% 
  dplyr::select(Status, `p adj`)

```

#### THC
```{r THC}

glm(THC ~ Status, data = df_hbox_impute) %>% summary()
aov(THC ~ Status, data = df_hbox_impute) %>% TukeyHSD() %>% 
  .$Status %>% 
  as.data.frame() %>% 
  rownames_to_column("Status") %>% 
  dplyr::select(Status, `p adj`)

```

#### OxyHb
```{r OxyHb}

glm(OxyHb ~ Status, data = df_hbox_impute) %>% summary()
aov(OxyHb ~ Status, data = df_hbox_impute) %>% TukeyHSD() %>% 
  .$Status %>% 
  as.data.frame() %>% 
  rownames_to_column("Status") %>% 
  dplyr::select(Status, `p adj`)

```

#### Lactate
```{r Lactate}

glm(Lactate ~ Status, data = df_hbox_impute) %>% summary()
aov(Lactate ~ Status, data = df_hbox_impute) %>% TukeyHSD() %>% 
  .$Status %>% 
  as.data.frame() %>% 
  rownames_to_column("Status") %>% 
  dplyr::select(Status, `p adj`)

```

#### ?OxyHb_alpha
```{r OxyHb_alpha}

glm(OxyHb_alpha ~ Status, data = df_hbox_impute) %>% summary()
aov(OxyHb_alpha ~ Status, data = df_hbox_impute) %>% TukeyHSD() %>% 
  .$Status %>% 
  as.data.frame() %>% 
  rownames_to_column("Status") %>% 
  dplyr::select(Status, `p adj`)

```





