on:
    workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Link cerebral_oxygenation repo with data on Dataverse
        uses: rlsmith1/cerebral_oxygenation
        with:
          DATAVERSE_TOKEN: fad3135f-e514-43c2-9241-5c98d1fa8a2c
          DATAVERSE_SERVER: https://dataverse.harvard.edu
          DATAVERSE_DATASET_DOI: doi:10.7910/DVN/JQDBIM
